---
# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: mysql
  :database: ynfb_development
  :username: root
  :password: 
  :host: localhost

:test:
  <<: *defaults
  :database: ynfb_test

:production:
  <<: *defaults
  :database: ynfb_production
  
:rake:
  <<: *defaults